# Generated by Django 4.2.7 on 2023-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('cantidad', models.BigIntegerField()),
                ('cod_tp_pago', models.IntegerField()),
            ],
        ),
    ]
