# Generated by Django 4.2.7 on 2024-03-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_movimiento_fecha_alter_movimiento_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierre_Diario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Ing_efectivo', models.BigIntegerField(blank=True, null=True)),
                ('Ing_POS', models.BigIntegerField(blank=True, null=True)),
                ('Ing_transferencia', models.BigIntegerField(blank=True, null=True)),
                ('Ing_abono', models.BigIntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
