# Generated by Django 4.2.7 on 2024-03-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_cierre_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre_diario',
            name='Ing_fondo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
