# Generated by Django 5.0.2 on 2024-07-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categoria_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estado_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mem_Ram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
                ('descrip_corta1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officeq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sis_Oper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_requerimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_soporte_correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='titulo_tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tp_manto_pc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tp_pc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('Usuario_AD', models.CharField(max_length=100)),
                ('Nom_Equipo_AD', models.CharField(max_length=100)),
                ('Ip_Asig', models.GenericIPAddressField()),
                ('Mac_Eth', models.CharField(max_length=17)),
                ('Antivirus', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('Almac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.almac')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.estado')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.marca')),
                ('Mem_Ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.mem_ram')),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.office')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico_tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch', models.DateField()),
                ('fallas', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('id_Computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='procedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=51)),
                ('descrip_larga', models.CharField(max_length=50)),
                ('cod_proced_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='modulos.procedencia')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='cod_proc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='Sis_Oper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.sis_oper'),
        ),
        migrations.CreateModel(
            name='Equip_Pers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_mac', models.CharField(max_length=17, unique=True)),
                ('direccion_ip', models.CharField(max_length=16, unique=True)),
                ('nom_equip_utm', models.CharField(max_length=100)),
                ('nom_completo', models.CharField(max_length=100)),
                ('fch_con', models.DateTimeField(auto_now_add=True)),
                ('obs', models.TextField()),
                ('cod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
                ('descrip_larga', models.TextField()),
                ('descrip_resol', models.TextField(blank=True, null=True)),
                ('num_exp', models.CharField(max_length=50)),
                ('fch_rec', models.DateField()),
                ('fch_fin', models.DateField(blank=True, null=True)),
                ('respo_rec', models.CharField(blank=True, max_length=50, null=True)),
                ('respo_ejec', models.CharField(blank=True, max_length=50, null=True)),
                ('img_req', models.FileField(blank=True, null=True, upload_to='Req_Rec/')),
                ('img_resol', models.FileField(blank=True, null=True, upload_to='Req_Resol/')),
                ('cod_cat_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.categoria_req')),
                ('cod_est_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.estado_req')),
                ('cod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
                ('cod_tp_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tipo_requerimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Soporte_Correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_correo', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=10)),
                ('fch_sop', models.DateField()),
                ('observ', models.TextField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tecnico')),
                ('tipo_sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tipo_soporte_correos')),
            ],
        ),
        migrations.CreateModel(
            name='Manto_Computadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('id_Computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.computadora')),
                ('tp_manto_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tp_manto_pc')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='Tipo_PC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tp_pc'),
        ),
    ]
