# Generated by Django 5.0.2 on 2024-05-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientos',
            name='img_req',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
