# Generated by Django 5.0.2 on 2024-10-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_diagnostico_tecnico_cod_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca_imp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='modelo_imp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tipo_imp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='impresora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.TextField()),
                ('responsable', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.estado')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.marca_imp')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.modelo_imp')),
                ('tp_imp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tipo_imp')),
            ],
        ),
    ]
