# Generated by Django 5.0.2 on 2024-05-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_alter_requerimientos_img_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimientos',
            name='img_req',
            field=models.ImageField(blank=True, null=True, upload_to='Req_Rec/'),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='img_resol',
            field=models.ImageField(blank=True, null=True, upload_to='Req_Resol/'),
        ),
    ]
