# Generated by Django 5.0.6 on 2024-06-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_requerimientos_img_req_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_soporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soporte_Correos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta_correo', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=50)),
                ('tecnico', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=10)),
                ('fch_sop', models.DateField()),
                ('tipo_soporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tipo_soporte')),
            ],
        ),
    ]
