# Generated by Django 5.0.2 on 2024-10-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_modelo_imp_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
