# Generated by Django 5.0.2 on 2024-06-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_alter_procedencia_cod_proced_superior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mem_Ram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sis_Oper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tp_pc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='descrip_larga',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='requerimientos',
            name='descrip_resol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('Usuario_AD', models.CharField(max_length=100)),
                ('Nom_Equipo_AD', models.CharField(max_length=100)),
                ('Ip_Asig', models.CharField(max_length=8)),
                ('Mac_Eth', models.CharField(max_length=16)),
                ('Antivirus', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('Almac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.almac')),
                ('cod_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.estado')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.marca')),
                ('Mem_Ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.mem_ram')),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.office')),
                ('Sis_Oper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.sis_oper')),
                ('Tipo_PC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tp_pc')),
            ],
        ),
    ]
