# Generated by Django 5.0.6 on 2024-06-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_tipo_soporte_soporte_correos'),
    ]

    operations = [
        migrations.AddField(
            model_name='soporte_correos',
            name='observ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
