# Generated by Django 5.0.6 on 2024-06-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_tipo_soporte_alter_requerimientos_descrip_larga_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tipo_soporte',
            new_name='tipo_soporte_correos',
        ),
    ]
