# Generated by Django 5.0.2 on 2024-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_almac_estado_marca_mem_ram_office_sis_oper_tp_pc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='Ip_Asig',
            field=models.GenericIPAddressField(),
        ),
    ]
