# Generated by Django 5.0.6 on 2024-06-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0006_soporte_correos_observ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soporte_correos',
            name='observ',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
