# Generated by Django 5.0.6 on 2024-06-12 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_rename_tipo_soporte_tipo_soporte_correos'),
    ]

    operations = [
        migrations.CreateModel(
            name='titulo_tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='soporte_correos',
            name='titulo_tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulos.titulo_tecnico'),
            preserve_default=False,
        ),
    ]
