# Generated by Django 5.0.2 on 2024-06-12 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_alter_computadora_ip_asig'),
    ]

    operations = [
        migrations.CreateModel(
            name='tp_manto_pc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manto_Computadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('id_Computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.computadora')),
                ('tp_manto_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tp_manto_pc')),
            ],
        ),
    ]
