# Generated by Django 5.0.6 on 2024-06-12 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_titulo_tecnico_soporte_correos_titulo_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='soporte_correos',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tecnico'),
        ),
    ]
