# Generated by Django 5.0.2 on 2024-06-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_tp_manto_pc_manto_computadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico_tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch', models.DateField()),
                ('fallas', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('id_Computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.computadora')),
            ],
        ),
    ]
