# Generated by Django 5.0.6 on 2024-06-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_tecnico_alter_soporte_correos_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soporte_correos',
            name='titulo_tecnico',
        ),
    ]
