# Generated by Django 5.0.2 on 2024-06-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_diagnostico_tecnico'),
        ('modulos', '0010_remove_soporte_correos_titulo_tecnico'),
    ]

    operations = [
    ]
