# Generated by Django 5.0.2 on 2024-06-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0012_equip_pers'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_pers',
            name='cod_proc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia'),
            preserve_default=False,
        ),
    ]
